---
- name: Auto-install Windows updates
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
  vars_files:
    - justin.vault
  tasks:
    - name: automatic update
      script: Automatic_Windows_Update.ps1 universe
      register: out
    - debug: var=out.stdout_lines
