---
- hosts: va
  become: yes
  tasks:
  - name: set min age
    command: chage -m 1 nwt
    async: 0
    poll: 0
    ignore_errors: true
  - name: set max age 
    command: chage -M 60 nwt
    async: 0
    poll: 0
    ignore_errors: true
     
