---
- name: Check for missing updates
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
  vars_files:
    - justin.vault
  tasks:
    - name: Check for missing updates
      win_updates: state=searched
      register: update_count
