---
- name: Install Windows updates 
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
  vars_files:
    - justinivv.vault
  tasks:
    - name: Install all security, critical, and rollup updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        log_path: c:\temp\ansible_wu.txt
      data: crash
      
