---
- hosts: va
  tasks:
  - name: edit yum.conf file 
    copy:
      src: /tmp/yum.conf
      dest: /etc/yum.conf
      mode: 0644
  - name: change nwt group
    command: chgrp users /home/nwt
  - name: change file group
    command: sudo chgrp users /home/admin/*
  - name: change user file permission
    command: chmod 0740 /home/nwt/.bash_logout
  - name: ntp syncronization
    command: echo maxpoll 10 /etc/ntp .conf
  - name: restart NTP service
    service:
      name: ntpd
      state: restarted
      enabled: yes
  - name: enable firewall rule
    command: firewall-cmd --direct --permanent --add-rule ipv4 filter IN_public_allow 0 -m tcp -p tcp -m limit --limit 25/minute --limit-burst 100 -j ACCEPT
  - name: restart firewall
    command: systemctl restart firewalld
  - name: make file immutable
    command: chattr +i /etc/resolv.conf
  - name: install multiple pkgs
    yum: name={{ item }} state=present
    with_items:
          - esc
          - authconfig
          - authconfig-gtk
          - pam_pkcs11
  - name: start tmp.mount service
    service:
      name: tmp.mount
      state: started
      enabled: yes
