---
- hosts: txqa
  become: yes
  tasks:
  - name: Install Packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - screen
      - aide
      - audit
  - name: push auditd.conf
    copy:
      src: ~nwt/qa/etc/audit/auditd.conf
      dest: /etc/audit/auditd.conf
      mode: 0640
  - name: push audit.conf
    copy:
      src: ~nwt/qa/etc/audit/audit.conf
      dest: /etc/audit/audit.conf
      mode: 0640
  - name: push audit.rules
    copy:
      src: ~nwt/qa/etc/audit/audit.rules
      dest: /etc/audit/audit.rules
      mode: 0600
  - name: push another audit.rules
    copy:
      src: ~nwt/qa/etc/audit/rules.d/audit.rules
      dest: /etc/audit/rules.d/audit.rules
      mode: 0600
  - name: restart auditd
    command: service auditd restart
  - name: push cron.daily
    copy:
      src: ~nwt/qa/etc/aide.conf
      dest: /etc/aide.conf
      mode: 0644
  - name: push rsyslog
    copy:
      src: ~nwt/qa/etc/rsyslog.conf
      dest: /etc/rsyslog.conf
      mode: 0644
  - name: push audisp.conf
    copy:
      src: ~nwt/qa/etc/audisp/audisp-remote.conf
      dest: /etc/audisp/audisp-remote.conf
      mode: 0640
  - name: push pam.d passwd
    copy:
      src: ~nwt/qa/etc/pam.d/passwd
      dest: /etc/pam.d/passwd
      mode: 0644
  - name: push pw security
    copy:
      src: ~nwt/qa/etc/security/pwquality.conf
      dest: /etc/security/pwquality.conf
      mode: 0644
  - name: push login banner
    copy:
      src: ~nwt/qa/etc/issue
      dest: /etc/issue
      mode: 0644
  - name: push system-auth-ac
    copy:
      src: ~nwt/qa/etc/pam.d/system-auth-ac
      dest: /etc/pam.d/system-auth-ac
      mode: 0644
  - name: push password-auth-ac
    copy:
      src: ~nwt/qa/etc/pam.d/password-auth-ac
      dest: /etc/pam.d/password-auth-ac
      mode: 0644
  - name: push login.defs
    copy:
      src: ~nwt/qa/etc/login.defs
      dest: /etc/login.defs
      mode: 0644
  - name: push sshd_config
    copy:
      src: ~nwt/qa/etc/ssh/sshd_config
      dest: /etc/ssh/sshd_config
      mode: 0600
  - name: pam sshd
    copy:
      src: ~nwt/qa/etc/pam.d/sshd
      dest: /etc/pam.d/sshd
      mode: 0644
  - name: set /etc/ssh/ssh_host_ed25519_key
    file: 
      path: /etc/ssh/ssh_host_ed25519_key
      mode: 0600
  - name: set /etc/ssh/ssh_host_ecdsa_key
    file:
      path: /etc/ssh/ssh_host_ecdsa_key
      mode: 0600
  - name: restart sshd
    command: systemctl restart sshd
  - name: push useradd
    copy:
      src: ~nwt/qa/etc/default/useradd
      dest: /etc/default/useradd
      mode: 0644
  - name: push yum.conf
    copy:
      src: ~nwt/qa/etc/yum.conf
      dest: /etc/yum.conf
      mode: 0644 
  - name: push blacklist.conf
    copy:
      src: ~nwt/qa/etc/modprobe.d/blacklist.conf
      dest: /etc/modprobe.d/blacklist.conf
      mode: 0644
  - name: push nodccp
    copy:
      src: ~nwt/qa/etc/modprobe.d/nodccp
      dest: /etc/modprobe.d/nodccp
      mode: 0644
  - name: push limits.conf
    copy:
      src: ~nwt/qa/etc/security/limits.conf
      dest: /etc/security/limits.conf
      mode: 0644
  - name: push profile
    copy:
      src: ~nwt/qa/etc/profile
      dest: /etc/profile
      mode: 0644
  - name: push sysctl.conf
    copy:
      src: ~nwt/qa/etc/sysctl.conf
      dest: /etc/sysctl.conf
      mode: 0644
  - name: enable sysctl settings
    command: sysctl -p
  - name: push postlogin-ac
    copy:
      src: ~nwt/qa/etc/pam.d/postlogin-ac
      dest: /etc/pam.d/postlogin-ac
      mode: 0644
  - name: push resolv.conf
    copy:
      src: ~nwt/qa/etc/resolv.conf
      dest: /etc/resolv.conf
      mode: 0644
  - name: set resolv mode
    command: chattr +i /etc/resolv.conf
