---
- hosts: vadevspe000000.dev.cms.radvcdat.com
  become_user: yes
  tasks:
  - name: Screen Installation
    yum:
      name: screen
      state: installed
  - name: push profile
    copy:
      src: /home/nwt/playbooks/ans-data/pwquality.conf
      dest: /etc/security/pwquality.conf
      mode: 0644
